/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/sites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sites
         * @description List all sites.
         *
         *     Optionally filter by link status (linked to Stashapp/StashDB or not).
         */
        get: operations["list_sites_sites_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Site
         * @description Get a specific site by UUID.
         */
        get: operations["get_site_sites__uuid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites/{uuid}/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Link Site
         * @description Link a site to an external system.
         */
        post: operations["link_site_sites__uuid__link_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LinkSiteRequest
         * @description Request body for linking a site to external systems.
         */
        LinkSiteRequest: {
            /**
             * Target
             * @description Target system name (stashapp or stashdb)
             */
            target: string;
            /**
             * External Id
             * @description External ID value
             */
            external_id: string;
        };
        /**
         * Site
         * @description Site response model.
         */
        Site: {
            /**
             * Ce Sites Uuid
             * @description Site UUID
             */
            ce_sites_uuid: string;
            /**
             * Ce Sites Short Name
             * @description Short name identifier
             */
            ce_sites_short_name: string;
            /**
             * Ce Sites Name
             * @description Full site name
             */
            ce_sites_name: string;
            /**
             * Ce Sites Url
             * @description Site URL
             */
            ce_sites_url: string;
        };
        /**
         * SiteDetail
         * @description Detailed site information including external IDs.
         */
        SiteDetail: {
            /**
             * Ce Sites Uuid
             * @description Site UUID
             */
            ce_sites_uuid: string;
            /**
             * Ce Sites Short Name
             * @description Short name identifier
             */
            ce_sites_short_name: string;
            /**
             * Ce Sites Name
             * @description Full site name
             */
            ce_sites_name: string;
            /**
             * Ce Sites Url
             * @description Site URL
             */
            ce_sites_url: string;
            /** @description External system IDs */
            external_ids: components["schemas"]["SiteExternalIds"];
        };
        /**
         * SiteExternalIds
         * @description External IDs for a site.
         */
        SiteExternalIds: {
            /**
             * Stashapp
             * @description Stashapp studio ID
             */
            stashapp?: string | null;
            /**
             * Stashdb
             * @description StashDB studio ID
             */
            stashdb?: string | null;
        };
        /**
         * SiteWithLinkStatus
         * @description Site with link status information.
         */
        SiteWithLinkStatus: {
            /**
             * Ce Sites Uuid
             * @description Site UUID
             */
            ce_sites_uuid: string;
            /**
             * Ce Sites Short Name
             * @description Short name identifier
             */
            ce_sites_short_name: string;
            /**
             * Ce Sites Name
             * @description Full site name
             */
            ce_sites_name: string;
            /**
             * Ce Sites Url
             * @description Site URL
             */
            ce_sites_url: string;
            /**
             * Has Stashapp Link
             * @description Whether site is linked to Stashapp
             */
            has_stashapp_link: boolean;
            /**
             * Has Stashdb Link
             * @description Whether site is linked to StashDB
             */
            has_stashdb_link: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_sites_sites_get: {
        parameters: {
            query?: {
                /** @description Filter by link status: true=linked, false=unlinked, null=all */
                linked?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Site"][] | components["schemas"]["SiteWithLinkStatus"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_site_sites__uuid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    link_site_sites__uuid__link_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkSiteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
