"""fix_tags_json_document_type

Revision ID: b5c8aff455af
Revises: 61f3ef54b0c6
Create Date: 2025-12-18 20:55:51.395123

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "b5c8aff455af"
down_revision: str | Sequence[str] | None = "61f3ef54b0c6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # First update any NULL values to empty JSON object
    op.execute("UPDATE tags SET json_document = '{}' WHERE json_document IS NULL")
    # Change type from TEXT to JSON using explicit cast
    op.execute("ALTER TABLE tags ALTER COLUMN json_document TYPE JSON USING json_document::json")
    # Set NOT NULL and server default
    op.alter_column("tags", "json_document",
               existing_type=sa.JSON(),
               nullable=False,
               server_default="{}")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tags", "json_document",
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
