// <auto-generated />
using System;
using CultureExtractor;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CultureExtractor.Migrations
{
    [DbContext(typeof(SqliteContext))]
    [Migration("20230123181323_DownloadOptions")]
    partial class DownloadOptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("CultureExtractor.DownloadEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DownloadOptions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DownloadQuality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DownloadedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFilename")
                        .HasColumnType("TEXT");

                    b.Property<string>("SavedFilename")
                        .HasColumnType("TEXT");

                    b.Property<int>("SceneId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SceneId");

                    b.ToTable("Downloads");
                });

            modelBuilder.Entity("CultureExtractor.DownloadOptionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codec")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("FileSize")
                        .HasColumnType("REAL");

                    b.Property<double?>("Fps")
                        .HasColumnType("REAL");

                    b.Property<int?>("ResolutionHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResolutionWidth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SceneEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SceneEntityId");

                    b.ToTable("DownloadOptions");
                });

            modelBuilder.Entity("CultureExtractor.GalleryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Pictures")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SiteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.ToTable("Galleries");
                });

            modelBuilder.Entity("CultureExtractor.SceneEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Duration")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SiteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.ToTable("Scenes");
                });

            modelBuilder.Entity("CultureExtractor.SiteEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("CultureExtractor.SitePerformerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GalleryEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .HasColumnType("TEXT");

                    b.Property<int>("SiteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GalleryEntityId");

                    b.HasIndex("SiteId");

                    b.ToTable("Performers");
                });

            modelBuilder.Entity("CultureExtractor.SiteTagEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GalleryEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .HasColumnType("TEXT");

                    b.Property<int>("SiteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GalleryEntityId");

                    b.HasIndex("SiteId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("CultureExtractor.StorageStateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SiteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StorageState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SiteId")
                        .IsUnique();

                    b.ToTable("StorageStates");
                });

            modelBuilder.Entity("SceneEntitySitePerformerEntity", b =>
                {
                    b.Property<int>("PerformersId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScenesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PerformersId", "ScenesId");

                    b.HasIndex("ScenesId");

                    b.ToTable("SceneEntitySitePerformerEntity");
                });

            modelBuilder.Entity("SceneEntitySiteTagEntity", b =>
                {
                    b.Property<int>("ScenesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ScenesId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("SceneEntitySiteTagEntity");
                });

            modelBuilder.Entity("CultureExtractor.DownloadEntity", b =>
                {
                    b.HasOne("CultureExtractor.SceneEntity", "Scene")
                        .WithMany("Downloads")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("CultureExtractor.DownloadOptionEntity", b =>
                {
                    b.HasOne("CultureExtractor.SceneEntity", null)
                        .WithMany("DownloadOptions")
                        .HasForeignKey("SceneEntityId");
                });

            modelBuilder.Entity("CultureExtractor.GalleryEntity", b =>
                {
                    b.HasOne("CultureExtractor.SiteEntity", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("CultureExtractor.SceneEntity", b =>
                {
                    b.HasOne("CultureExtractor.SiteEntity", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("CultureExtractor.SitePerformerEntity", b =>
                {
                    b.HasOne("CultureExtractor.GalleryEntity", null)
                        .WithMany("Performers")
                        .HasForeignKey("GalleryEntityId");

                    b.HasOne("CultureExtractor.SiteEntity", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("CultureExtractor.SiteTagEntity", b =>
                {
                    b.HasOne("CultureExtractor.GalleryEntity", null)
                        .WithMany("Tags")
                        .HasForeignKey("GalleryEntityId");

                    b.HasOne("CultureExtractor.SiteEntity", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("CultureExtractor.StorageStateEntity", b =>
                {
                    b.HasOne("CultureExtractor.SiteEntity", "Site")
                        .WithOne("StorageState")
                        .HasForeignKey("CultureExtractor.StorageStateEntity", "SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("SceneEntitySitePerformerEntity", b =>
                {
                    b.HasOne("CultureExtractor.SitePerformerEntity", null)
                        .WithMany()
                        .HasForeignKey("PerformersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CultureExtractor.SceneEntity", null)
                        .WithMany()
                        .HasForeignKey("ScenesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SceneEntitySiteTagEntity", b =>
                {
                    b.HasOne("CultureExtractor.SceneEntity", null)
                        .WithMany()
                        .HasForeignKey("ScenesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CultureExtractor.SiteTagEntity", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CultureExtractor.GalleryEntity", b =>
                {
                    b.Navigation("Performers");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("CultureExtractor.SceneEntity", b =>
                {
                    b.Navigation("DownloadOptions");

                    b.Navigation("Downloads");
                });

            modelBuilder.Entity("CultureExtractor.SiteEntity", b =>
                {
                    b.Navigation("StorageState");
                });
#pragma warning restore 612, 618
        }
    }
}
