// <auto-generated />
using System;
using CultureExtractor;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CultureExtractor.Migrations
{
    [DbContext(typeof(SqliteContext))]
    [Migration("20231109073203_FileTypeContentTypeForDownloads")]
    partial class FileTypeContentTypeForDownloads
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("CultureExtractor.DownloadEntity", b =>
                {
                    b.Property<string>("Uuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("AvailableFile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DownloadedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFilename")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseUuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SavedFilename")
                        .HasColumnType("TEXT");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Uuid");

                    b.HasIndex("ReleaseUuid");

                    b.ToTable("Downloads");
                });

            modelBuilder.Entity("CultureExtractor.ReleaseEntity", b =>
                {
                    b.Property<string>("Uuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("AvailableFiles")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Duration")
                        .HasColumnType("REAL");

                    b.Property<string>("JsonDocument")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteUuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubSiteUuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Uuid");

                    b.HasIndex("SiteUuid");

                    b.HasIndex("SubSiteUuid");

                    b.ToTable("Releases");
                });

            modelBuilder.Entity("CultureExtractor.SiteEntity", b =>
                {
                    b.Property<string>("Uuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Uuid");

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("CultureExtractor.SitePerformerEntity", b =>
                {
                    b.Property<string>("Uuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteUuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Uuid");

                    b.HasIndex("SiteUuid");

                    b.ToTable("Performers");
                });

            modelBuilder.Entity("CultureExtractor.SiteTagEntity", b =>
                {
                    b.Property<string>("Uuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteUuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Uuid");

                    b.HasIndex("SiteUuid");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("CultureExtractor.StorageStateEntity", b =>
                {
                    b.Property<string>("Uuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteUuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Uuid");

                    b.HasIndex("SiteUuid")
                        .IsUnique();

                    b.ToTable("StorageStates");
                });

            modelBuilder.Entity("CultureExtractor.SubSiteEntity", b =>
                {
                    b.Property<string>("Uuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteUuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Uuid");

                    b.HasIndex("SiteUuid");

                    b.ToTable("SubSites");
                });

            modelBuilder.Entity("ReleaseEntitySitePerformerEntity", b =>
                {
                    b.Property<string>("PerformersUuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleasesUuid")
                        .HasColumnType("TEXT");

                    b.HasKey("PerformersUuid", "ReleasesUuid");

                    b.HasIndex("ReleasesUuid");

                    b.ToTable("ReleaseEntitySitePerformerEntity");
                });

            modelBuilder.Entity("ReleaseEntitySiteTagEntity", b =>
                {
                    b.Property<string>("ReleasesUuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("TagsUuid")
                        .HasColumnType("TEXT");

                    b.HasKey("ReleasesUuid", "TagsUuid");

                    b.HasIndex("TagsUuid");

                    b.ToTable("ReleaseEntitySiteTagEntity");
                });

            modelBuilder.Entity("CultureExtractor.DownloadEntity", b =>
                {
                    b.HasOne("CultureExtractor.ReleaseEntity", "Release")
                        .WithMany("Downloads")
                        .HasForeignKey("ReleaseUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Release");
                });

            modelBuilder.Entity("CultureExtractor.ReleaseEntity", b =>
                {
                    b.HasOne("CultureExtractor.SiteEntity", "Site")
                        .WithMany()
                        .HasForeignKey("SiteUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CultureExtractor.SubSiteEntity", "SubSite")
                        .WithMany()
                        .HasForeignKey("SubSiteUuid");

                    b.Navigation("Site");

                    b.Navigation("SubSite");
                });

            modelBuilder.Entity("CultureExtractor.SitePerformerEntity", b =>
                {
                    b.HasOne("CultureExtractor.SiteEntity", "Site")
                        .WithMany()
                        .HasForeignKey("SiteUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("CultureExtractor.SiteTagEntity", b =>
                {
                    b.HasOne("CultureExtractor.SiteEntity", "Site")
                        .WithMany()
                        .HasForeignKey("SiteUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("CultureExtractor.StorageStateEntity", b =>
                {
                    b.HasOne("CultureExtractor.SiteEntity", "Site")
                        .WithOne("StorageState")
                        .HasForeignKey("CultureExtractor.StorageStateEntity", "SiteUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("CultureExtractor.SubSiteEntity", b =>
                {
                    b.HasOne("CultureExtractor.SiteEntity", "Site")
                        .WithMany()
                        .HasForeignKey("SiteUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("ReleaseEntitySitePerformerEntity", b =>
                {
                    b.HasOne("CultureExtractor.SitePerformerEntity", null)
                        .WithMany()
                        .HasForeignKey("PerformersUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CultureExtractor.ReleaseEntity", null)
                        .WithMany()
                        .HasForeignKey("ReleasesUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReleaseEntitySiteTagEntity", b =>
                {
                    b.HasOne("CultureExtractor.ReleaseEntity", null)
                        .WithMany()
                        .HasForeignKey("ReleasesUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CultureExtractor.SiteTagEntity", null)
                        .WithMany()
                        .HasForeignKey("TagsUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CultureExtractor.ReleaseEntity", b =>
                {
                    b.Navigation("Downloads");
                });

            modelBuilder.Entity("CultureExtractor.SiteEntity", b =>
                {
                    b.Navigation("StorageState");
                });
#pragma warning restore 612, 618
        }
    }
}
