// <auto-generated />
using System;
using CultureExtractor;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CultureExtractor.Migrations
{
    [DbContext(typeof(SqliteContext))]
    [Migration("20231103061228_TagsUuidAvailable")]
    partial class TagsUuidAvailable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("CultureExtractor.DownloadEntity", b =>
                {
                    b.Property<string>("Uuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("DownloadOptions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DownloadQuality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DownloadedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFilename")
                        .HasColumnType("TEXT");

                    b.Property<string>("SavedFilename")
                        .HasColumnType("TEXT");

                    b.Property<string>("SceneUuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Uuid");

                    b.HasIndex("SceneUuid");

                    b.ToTable("Downloads");
                });

            modelBuilder.Entity("CultureExtractor.SceneEntity", b =>
                {
                    b.Property<string>("Uuid")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DownloadOptions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Duration")
                        .HasColumnType("REAL");

                    b.Property<string>("JsonDocument")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SiteId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SubSiteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Uuid");

                    b.HasIndex("SiteId");

                    b.HasIndex("SubSiteId");

                    b.ToTable("Scenes");
                });

            modelBuilder.Entity("CultureExtractor.SiteEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("CultureExtractor.SitePerformerEntity", b =>
                {
                    b.Property<string>("Uuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .HasColumnType("TEXT");

                    b.Property<int>("SiteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Uuid");

                    b.HasIndex("SiteId");

                    b.ToTable("Performers");
                });

            modelBuilder.Entity("CultureExtractor.SiteTagEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .HasColumnType("TEXT");

                    b.Property<int>("SiteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("CultureExtractor.StorageStateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SiteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StorageState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SiteId")
                        .IsUnique();

                    b.ToTable("StorageStates");
                });

            modelBuilder.Entity("CultureExtractor.SubSiteEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SiteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.ToTable("SubSites");
                });

            modelBuilder.Entity("SceneEntitySitePerformerEntity", b =>
                {
                    b.Property<string>("PerformersUuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScenesUuid")
                        .HasColumnType("TEXT");

                    b.HasKey("PerformersUuid", "ScenesUuid");

                    b.HasIndex("ScenesUuid");

                    b.ToTable("SceneEntitySitePerformerEntity");
                });

            modelBuilder.Entity("SceneEntitySiteTagEntity", b =>
                {
                    b.Property<string>("ScenesUuid")
                        .HasColumnType("TEXT");

                    b.Property<int>("TagsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ScenesUuid", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("SceneEntitySiteTagEntity");
                });

            modelBuilder.Entity("CultureExtractor.DownloadEntity", b =>
                {
                    b.HasOne("CultureExtractor.SceneEntity", "Scene")
                        .WithMany("Downloads")
                        .HasForeignKey("SceneUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("CultureExtractor.SceneEntity", b =>
                {
                    b.HasOne("CultureExtractor.SiteEntity", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CultureExtractor.SubSiteEntity", "SubSite")
                        .WithMany()
                        .HasForeignKey("SubSiteId");

                    b.Navigation("Site");

                    b.Navigation("SubSite");
                });

            modelBuilder.Entity("CultureExtractor.SitePerformerEntity", b =>
                {
                    b.HasOne("CultureExtractor.SiteEntity", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("CultureExtractor.SiteTagEntity", b =>
                {
                    b.HasOne("CultureExtractor.SiteEntity", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("CultureExtractor.StorageStateEntity", b =>
                {
                    b.HasOne("CultureExtractor.SiteEntity", "Site")
                        .WithOne("StorageState")
                        .HasForeignKey("CultureExtractor.StorageStateEntity", "SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("CultureExtractor.SubSiteEntity", b =>
                {
                    b.HasOne("CultureExtractor.SiteEntity", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("SceneEntitySitePerformerEntity", b =>
                {
                    b.HasOne("CultureExtractor.SitePerformerEntity", null)
                        .WithMany()
                        .HasForeignKey("PerformersUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CultureExtractor.SceneEntity", null)
                        .WithMany()
                        .HasForeignKey("ScenesUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SceneEntitySiteTagEntity", b =>
                {
                    b.HasOne("CultureExtractor.SceneEntity", null)
                        .WithMany()
                        .HasForeignKey("ScenesUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CultureExtractor.SiteTagEntity", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CultureExtractor.SceneEntity", b =>
                {
                    b.Navigation("Downloads");
                });

            modelBuilder.Entity("CultureExtractor.SiteEntity", b =>
                {
                    b.Navigation("StorageState");
                });
#pragma warning restore 612, 618
        }
    }
}
