// <auto-generated />
using System;
using CultureExtractor;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CultureExtractor.Migrations
{
    [DbContext(typeof(CultureExtractorContext))]
    [Migration("20231114100240_UseStringForJsonDueToPolymorphicSerializationIssues")]
    partial class UseStringForJsonDueToPolymorphicSerializationIssues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CultureExtractor.DownloadEntity", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<string>("AvailableFile")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("available_file");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("DownloadedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("downloaded_at");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_type");

                    b.Property<string>("OriginalFilename")
                        .HasColumnType("text")
                        .HasColumnName("original_filename");

                    b.Property<Guid>("ReleaseUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("release_uuid");

                    b.Property<string>("SavedFilename")
                        .HasColumnType("text")
                        .HasColumnName("saved_filename");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("variant");

                    b.HasKey("Uuid")
                        .HasName("pk_downloads");

                    b.HasIndex("ReleaseUuid")
                        .HasDatabaseName("ix_downloads_release_uuid");

                    b.ToTable("downloads", (string)null);
                });

            modelBuilder.Entity("CultureExtractor.ReleaseEntity", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<string>("AvailableFiles")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("available_files");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp")
                        .HasColumnName("created");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<double>("Duration")
                        .HasColumnType("double precision")
                        .HasColumnName("duration");

                    b.Property<string>("JsonDocument")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("json_document");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp")
                        .HasColumnName("last_updated");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("short_name");

                    b.Property<Guid>("SiteUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("site_uuid");

                    b.Property<Guid?>("SubSiteUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("sub_site_uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Uuid")
                        .HasName("pk_releases");

                    b.HasIndex("SiteUuid")
                        .HasDatabaseName("ix_releases_site_uuid");

                    b.HasIndex("SubSiteUuid")
                        .HasDatabaseName("ix_releases_sub_site_uuid");

                    b.ToTable("releases", (string)null);
                });

            modelBuilder.Entity("CultureExtractor.SiteEntity", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("short_name");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Uuid")
                        .HasName("pk_sites");

                    b.ToTable("sites", (string)null);
                });

            modelBuilder.Entity("CultureExtractor.SitePerformerEntity", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ShortName")
                        .HasColumnType("text")
                        .HasColumnName("short_name");

                    b.Property<Guid>("SiteUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("site_uuid");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Uuid")
                        .HasName("pk_performers");

                    b.HasIndex("SiteUuid")
                        .HasDatabaseName("ix_performers_site_uuid");

                    b.ToTable("performers", (string)null);
                });

            modelBuilder.Entity("CultureExtractor.SiteTagEntity", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ShortName")
                        .HasColumnType("text")
                        .HasColumnName("short_name");

                    b.Property<Guid>("SiteUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("site_uuid");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Uuid")
                        .HasName("pk_tags");

                    b.HasIndex("SiteUuid")
                        .HasDatabaseName("ix_tags_site_uuid");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("CultureExtractor.StorageStateEntity", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<Guid>("SiteUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("site_uuid");

                    b.Property<string>("StorageState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_state");

                    b.HasKey("Uuid")
                        .HasName("pk_storage_states");

                    b.HasIndex("SiteUuid")
                        .IsUnique()
                        .HasDatabaseName("ix_storage_states_site_uuid");

                    b.ToTable("storage_states", (string)null);
                });

            modelBuilder.Entity("CultureExtractor.SubSiteEntity", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("short_name");

                    b.Property<Guid>("SiteUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("site_uuid");

                    b.HasKey("Uuid")
                        .HasName("pk_sub_sites");

                    b.HasIndex("SiteUuid")
                        .HasDatabaseName("ix_sub_sites_site_uuid");

                    b.ToTable("sub_sites", (string)null);
                });

            modelBuilder.Entity("ReleaseEntitySitePerformerEntity", b =>
                {
                    b.Property<Guid>("PerformersUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("performers_uuid");

                    b.Property<Guid>("ReleasesUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("releases_uuid");

                    b.HasKey("PerformersUuid", "ReleasesUuid")
                        .HasName("pk_release_entity_site_performer_entity");

                    b.HasIndex("ReleasesUuid")
                        .HasDatabaseName("ix_release_entity_site_performer_entity_releases_uuid");

                    b.ToTable("release_entity_site_performer_entity", (string)null);
                });

            modelBuilder.Entity("ReleaseEntitySiteTagEntity", b =>
                {
                    b.Property<Guid>("ReleasesUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("releases_uuid");

                    b.Property<Guid>("TagsUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("tags_uuid");

                    b.HasKey("ReleasesUuid", "TagsUuid")
                        .HasName("pk_release_entity_site_tag_entity");

                    b.HasIndex("TagsUuid")
                        .HasDatabaseName("ix_release_entity_site_tag_entity_tags_uuid");

                    b.ToTable("release_entity_site_tag_entity", (string)null);
                });

            modelBuilder.Entity("CultureExtractor.DownloadEntity", b =>
                {
                    b.HasOne("CultureExtractor.ReleaseEntity", "Release")
                        .WithMany("Downloads")
                        .HasForeignKey("ReleaseUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_downloads_releases_release_temp_id");

                    b.Navigation("Release");
                });

            modelBuilder.Entity("CultureExtractor.ReleaseEntity", b =>
                {
                    b.HasOne("CultureExtractor.SiteEntity", "Site")
                        .WithMany()
                        .HasForeignKey("SiteUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_releases_sites_site_temp_id1");

                    b.HasOne("CultureExtractor.SubSiteEntity", "SubSite")
                        .WithMany()
                        .HasForeignKey("SubSiteUuid")
                        .HasConstraintName("fk_releases_sub_sites_sub_site_temp_id");

                    b.Navigation("Site");

                    b.Navigation("SubSite");
                });

            modelBuilder.Entity("CultureExtractor.SitePerformerEntity", b =>
                {
                    b.HasOne("CultureExtractor.SiteEntity", "Site")
                        .WithMany()
                        .HasForeignKey("SiteUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_performers_sites_site_temp_id");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("CultureExtractor.SiteTagEntity", b =>
                {
                    b.HasOne("CultureExtractor.SiteEntity", "Site")
                        .WithMany()
                        .HasForeignKey("SiteUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tags_sites_site_uuid");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("CultureExtractor.StorageStateEntity", b =>
                {
                    b.HasOne("CultureExtractor.SiteEntity", "Site")
                        .WithOne("StorageState")
                        .HasForeignKey("CultureExtractor.StorageStateEntity", "SiteUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_storage_states_sites_site_uuid");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("CultureExtractor.SubSiteEntity", b =>
                {
                    b.HasOne("CultureExtractor.SiteEntity", "Site")
                        .WithMany()
                        .HasForeignKey("SiteUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sub_sites_sites_site_uuid");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("ReleaseEntitySitePerformerEntity", b =>
                {
                    b.HasOne("CultureExtractor.SitePerformerEntity", null)
                        .WithMany()
                        .HasForeignKey("PerformersUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_release_entity_site_performer_entity_performers_performers_");

                    b.HasOne("CultureExtractor.ReleaseEntity", null)
                        .WithMany()
                        .HasForeignKey("ReleasesUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_release_entity_site_performer_entity_releases_releases_uuid");
                });

            modelBuilder.Entity("ReleaseEntitySiteTagEntity", b =>
                {
                    b.HasOne("CultureExtractor.ReleaseEntity", null)
                        .WithMany()
                        .HasForeignKey("ReleasesUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_release_entity_site_tag_entity_releases_releases_uuid");

                    b.HasOne("CultureExtractor.SiteTagEntity", null)
                        .WithMany()
                        .HasForeignKey("TagsUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_release_entity_site_tag_entity_tags_tags_uuid");
                });

            modelBuilder.Entity("CultureExtractor.ReleaseEntity", b =>
                {
                    b.Navigation("Downloads");
                });

            modelBuilder.Entity("CultureExtractor.SiteEntity", b =>
                {
                    b.Navigation("StorageState");
                });
#pragma warning restore 612, 618
        }
    }
}
