// <auto-generated />
using System;
using CultureExtractor;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CultureExtractor.Migrations
{
    [DbContext(typeof(CultureExtractorContext))]
    [Migration("20251218101249_AddDownloadUuidToReleaseExternalIds")]
    partial class AddDownloadUuidToReleaseExternalIds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CultureExtractor.DownloadEntity", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<string>("AvailableFile")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("available_file");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("DownloadedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("downloaded_at");

                    b.Property<string>("FileMetadata")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("file_metadata");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_type");

                    b.Property<string>("OriginalFilename")
                        .HasColumnType("text")
                        .HasColumnName("original_filename");

                    b.Property<Guid>("ReleaseUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("release_uuid");

                    b.Property<string>("SavedFilename")
                        .HasColumnType("text")
                        .HasColumnName("saved_filename");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("variant");

                    b.HasKey("Uuid")
                        .HasName("pk_downloads");

                    b.HasIndex("ReleaseUuid")
                        .HasDatabaseName("ix_downloads_release_uuid");

                    b.ToTable("downloads", (string)null);
                });

            modelBuilder.Entity("CultureExtractor.PerformerExternalIdEntity", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp")
                        .HasColumnName("created");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp")
                        .HasColumnName("last_updated");

                    b.Property<Guid>("PerformerUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("performer_uuid");

                    b.Property<Guid>("TargetSystemUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("target_system_uuid");

                    b.HasKey("Uuid")
                        .HasName("pk_performer_external_ids");

                    b.HasIndex("TargetSystemUuid")
                        .HasDatabaseName("ix_performer_external_ids_target_system_uuid");

                    b.HasIndex("PerformerUuid", "TargetSystemUuid")
                        .IsUnique()
                        .HasDatabaseName("ix_performer_external_ids_performer_uuid_target_system_uuid");

                    b.ToTable("performer_external_ids", (string)null);
                });

            modelBuilder.Entity("CultureExtractor.ReleaseEntity", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<string>("AvailableFiles")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("available_files");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp")
                        .HasColumnName("created");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<double>("Duration")
                        .HasColumnType("double precision")
                        .HasColumnName("duration");

                    b.Property<string>("JsonDocument")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("json_document");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp")
                        .HasColumnName("last_updated");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("short_name");

                    b.Property<Guid>("SiteUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("site_uuid");

                    b.Property<Guid?>("SubSiteUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("sub_site_uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Uuid")
                        .HasName("pk_releases");

                    b.HasIndex("SiteUuid")
                        .HasDatabaseName("ix_releases_site_uuid");

                    b.HasIndex("SubSiteUuid")
                        .HasDatabaseName("ix_releases_sub_site_uuid");

                    b.ToTable("releases", (string)null);
                });

            modelBuilder.Entity("CultureExtractor.ReleaseExternalIdEntity", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp")
                        .HasColumnName("created");

                    b.Property<Guid?>("DownloadUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("download_uuid");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp")
                        .HasColumnName("last_updated");

                    b.Property<Guid>("ReleaseUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("release_uuid");

                    b.Property<Guid>("TargetSystemUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("target_system_uuid");

                    b.HasKey("Uuid")
                        .HasName("pk_release_external_ids");

                    b.HasIndex("DownloadUuid")
                        .HasDatabaseName("ix_release_external_ids_download_uuid");

                    b.HasIndex("TargetSystemUuid")
                        .HasDatabaseName("ix_release_external_ids_target_system_uuid");

                    b.HasIndex("ReleaseUuid", "TargetSystemUuid", "DownloadUuid")
                        .IsUnique()
                        .HasDatabaseName("ix_release_external_ids_release_uuid_target_system_uuid_downlo");

                    b.ToTable("release_external_ids", (string)null);
                });

            modelBuilder.Entity("CultureExtractor.SiteEntity", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("short_name");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Uuid")
                        .HasName("pk_sites");

                    b.ToTable("sites", (string)null);
                });

            modelBuilder.Entity("CultureExtractor.SiteExternalIdEntity", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp")
                        .HasColumnName("created");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp")
                        .HasColumnName("last_updated");

                    b.Property<Guid>("SiteUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("site_uuid");

                    b.Property<Guid>("TargetSystemUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("target_system_uuid");

                    b.HasKey("Uuid")
                        .HasName("pk_site_external_ids");

                    b.HasIndex("TargetSystemUuid")
                        .HasDatabaseName("ix_site_external_ids_target_system_uuid");

                    b.HasIndex("SiteUuid", "TargetSystemUuid")
                        .IsUnique()
                        .HasDatabaseName("ix_site_external_ids_site_uuid_target_system_uuid");

                    b.ToTable("site_external_ids", (string)null);
                });

            modelBuilder.Entity("CultureExtractor.SitePerformerEntity", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<string>("JsonDocument")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("json_document");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ShortName")
                        .HasColumnType("text")
                        .HasColumnName("short_name");

                    b.Property<Guid>("SiteUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("site_uuid");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Uuid")
                        .HasName("pk_performers");

                    b.HasIndex("SiteUuid")
                        .HasDatabaseName("ix_performers_site_uuid");

                    b.ToTable("performers", (string)null);
                });

            modelBuilder.Entity("CultureExtractor.SiteTagEntity", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ShortName")
                        .HasColumnType("text")
                        .HasColumnName("short_name");

                    b.Property<Guid>("SiteUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("site_uuid");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Uuid")
                        .HasName("pk_tags");

                    b.HasIndex("SiteUuid")
                        .HasDatabaseName("ix_tags_site_uuid");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("CultureExtractor.StorageStateEntity", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<Guid>("SiteUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("site_uuid");

                    b.Property<string>("StorageState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_state");

                    b.HasKey("Uuid")
                        .HasName("pk_storage_states");

                    b.HasIndex("SiteUuid")
                        .IsUnique()
                        .HasDatabaseName("ix_storage_states_site_uuid");

                    b.ToTable("storage_states", (string)null);
                });

            modelBuilder.Entity("CultureExtractor.SubSiteEntity", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<string>("JsonDocument")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("json_document");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("short_name");

                    b.Property<Guid>("SiteUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("site_uuid");

                    b.HasKey("Uuid")
                        .HasName("pk_sub_sites");

                    b.HasIndex("SiteUuid")
                        .HasDatabaseName("ix_sub_sites_site_uuid");

                    b.ToTable("sub_sites", (string)null);
                });

            modelBuilder.Entity("CultureExtractor.SubSiteExternalIdEntity", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp")
                        .HasColumnName("created");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp")
                        .HasColumnName("last_updated");

                    b.Property<Guid>("SubSiteUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("sub_site_uuid");

                    b.Property<Guid>("TargetSystemUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("target_system_uuid");

                    b.HasKey("Uuid")
                        .HasName("pk_sub_site_external_ids");

                    b.HasIndex("TargetSystemUuid")
                        .HasDatabaseName("ix_sub_site_external_ids_target_system_uuid");

                    b.HasIndex("SubSiteUuid", "TargetSystemUuid")
                        .IsUnique()
                        .HasDatabaseName("ix_sub_site_external_ids_sub_site_uuid_target_system_uuid");

                    b.ToTable("sub_site_external_ids", (string)null);
                });

            modelBuilder.Entity("CultureExtractor.TagExternalIdEntity", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp")
                        .HasColumnName("created");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp")
                        .HasColumnName("last_updated");

                    b.Property<Guid>("TagUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_uuid");

                    b.Property<Guid>("TargetSystemUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("target_system_uuid");

                    b.HasKey("Uuid")
                        .HasName("pk_tag_external_ids");

                    b.HasIndex("TargetSystemUuid")
                        .HasDatabaseName("ix_tag_external_ids_target_system_uuid");

                    b.HasIndex("TagUuid", "TargetSystemUuid")
                        .IsUnique()
                        .HasDatabaseName("ix_tag_external_ids_tag_uuid_target_system_uuid");

                    b.ToTable("tag_external_ids", (string)null);
                });

            modelBuilder.Entity("CultureExtractor.TargetSystemEntity", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp")
                        .HasColumnName("created");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp")
                        .HasColumnName("last_updated");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Uuid")
                        .HasName("pk_target_systems");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_target_systems_name");

                    b.ToTable("target_systems", (string)null);
                });

            modelBuilder.Entity("ReleaseEntitySitePerformerEntity", b =>
                {
                    b.Property<Guid>("PerformersUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("performers_uuid");

                    b.Property<Guid>("ReleasesUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("releases_uuid");

                    b.HasKey("PerformersUuid", "ReleasesUuid")
                        .HasName("pk_release_entity_site_performer_entity");

                    b.HasIndex("ReleasesUuid")
                        .HasDatabaseName("ix_release_entity_site_performer_entity_releases_uuid");

                    b.ToTable("release_entity_site_performer_entity", (string)null);
                });

            modelBuilder.Entity("ReleaseEntitySiteTagEntity", b =>
                {
                    b.Property<Guid>("ReleasesUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("releases_uuid");

                    b.Property<Guid>("TagsUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("tags_uuid");

                    b.HasKey("ReleasesUuid", "TagsUuid")
                        .HasName("pk_release_entity_site_tag_entity");

                    b.HasIndex("TagsUuid")
                        .HasDatabaseName("ix_release_entity_site_tag_entity_tags_uuid");

                    b.ToTable("release_entity_site_tag_entity", (string)null);
                });

            modelBuilder.Entity("CultureExtractor.DownloadEntity", b =>
                {
                    b.HasOne("CultureExtractor.ReleaseEntity", "Release")
                        .WithMany("Downloads")
                        .HasForeignKey("ReleaseUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_downloads_releases_release_uuid");

                    b.Navigation("Release");
                });

            modelBuilder.Entity("CultureExtractor.PerformerExternalIdEntity", b =>
                {
                    b.HasOne("CultureExtractor.SitePerformerEntity", "Performer")
                        .WithMany("ExternalIds")
                        .HasForeignKey("PerformerUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_performer_external_ids_performers_performer_uuid");

                    b.HasOne("CultureExtractor.TargetSystemEntity", "TargetSystem")
                        .WithMany()
                        .HasForeignKey("TargetSystemUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_performer_external_ids_target_systems_target_system_uuid");

                    b.Navigation("Performer");

                    b.Navigation("TargetSystem");
                });

            modelBuilder.Entity("CultureExtractor.ReleaseEntity", b =>
                {
                    b.HasOne("CultureExtractor.SiteEntity", "Site")
                        .WithMany()
                        .HasForeignKey("SiteUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_releases_sites_site_uuid");

                    b.HasOne("CultureExtractor.SubSiteEntity", "SubSite")
                        .WithMany()
                        .HasForeignKey("SubSiteUuid")
                        .HasConstraintName("fk_releases_sub_sites_sub_site_uuid");

                    b.Navigation("Site");

                    b.Navigation("SubSite");
                });

            modelBuilder.Entity("CultureExtractor.ReleaseExternalIdEntity", b =>
                {
                    b.HasOne("CultureExtractor.DownloadEntity", "Download")
                        .WithMany()
                        .HasForeignKey("DownloadUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_release_external_ids_downloads_download_uuid");

                    b.HasOne("CultureExtractor.ReleaseEntity", "Release")
                        .WithMany("ExternalIds")
                        .HasForeignKey("ReleaseUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_release_external_ids_releases_release_uuid");

                    b.HasOne("CultureExtractor.TargetSystemEntity", "TargetSystem")
                        .WithMany()
                        .HasForeignKey("TargetSystemUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_release_external_ids_target_systems_target_system_uuid");

                    b.Navigation("Download");

                    b.Navigation("Release");

                    b.Navigation("TargetSystem");
                });

            modelBuilder.Entity("CultureExtractor.SiteExternalIdEntity", b =>
                {
                    b.HasOne("CultureExtractor.SiteEntity", "Site")
                        .WithMany("ExternalIds")
                        .HasForeignKey("SiteUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_site_external_ids_sites_site_uuid");

                    b.HasOne("CultureExtractor.TargetSystemEntity", "TargetSystem")
                        .WithMany()
                        .HasForeignKey("TargetSystemUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_site_external_ids_target_systems_target_system_uuid");

                    b.Navigation("Site");

                    b.Navigation("TargetSystem");
                });

            modelBuilder.Entity("CultureExtractor.SitePerformerEntity", b =>
                {
                    b.HasOne("CultureExtractor.SiteEntity", "Site")
                        .WithMany()
                        .HasForeignKey("SiteUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_performers_sites_site_uuid");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("CultureExtractor.SiteTagEntity", b =>
                {
                    b.HasOne("CultureExtractor.SiteEntity", "Site")
                        .WithMany()
                        .HasForeignKey("SiteUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tags_sites_site_uuid");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("CultureExtractor.StorageStateEntity", b =>
                {
                    b.HasOne("CultureExtractor.SiteEntity", "Site")
                        .WithOne("StorageState")
                        .HasForeignKey("CultureExtractor.StorageStateEntity", "SiteUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_storage_states_sites_site_uuid");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("CultureExtractor.SubSiteEntity", b =>
                {
                    b.HasOne("CultureExtractor.SiteEntity", "Site")
                        .WithMany()
                        .HasForeignKey("SiteUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sub_sites_sites_site_uuid");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("CultureExtractor.SubSiteExternalIdEntity", b =>
                {
                    b.HasOne("CultureExtractor.SubSiteEntity", "SubSite")
                        .WithMany("ExternalIds")
                        .HasForeignKey("SubSiteUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sub_site_external_ids_sub_sites_sub_site_uuid");

                    b.HasOne("CultureExtractor.TargetSystemEntity", "TargetSystem")
                        .WithMany()
                        .HasForeignKey("TargetSystemUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sub_site_external_ids_target_systems_target_system_uuid");

                    b.Navigation("SubSite");

                    b.Navigation("TargetSystem");
                });

            modelBuilder.Entity("CultureExtractor.TagExternalIdEntity", b =>
                {
                    b.HasOne("CultureExtractor.SiteTagEntity", "Tag")
                        .WithMany("ExternalIds")
                        .HasForeignKey("TagUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tag_external_ids_tags_tag_uuid");

                    b.HasOne("CultureExtractor.TargetSystemEntity", "TargetSystem")
                        .WithMany()
                        .HasForeignKey("TargetSystemUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tag_external_ids_target_systems_target_system_uuid");

                    b.Navigation("Tag");

                    b.Navigation("TargetSystem");
                });

            modelBuilder.Entity("ReleaseEntitySitePerformerEntity", b =>
                {
                    b.HasOne("CultureExtractor.SitePerformerEntity", null)
                        .WithMany()
                        .HasForeignKey("PerformersUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_release_entity_site_performer_entity_performers_performers_");

                    b.HasOne("CultureExtractor.ReleaseEntity", null)
                        .WithMany()
                        .HasForeignKey("ReleasesUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_release_entity_site_performer_entity_releases_releases_uuid");
                });

            modelBuilder.Entity("ReleaseEntitySiteTagEntity", b =>
                {
                    b.HasOne("CultureExtractor.ReleaseEntity", null)
                        .WithMany()
                        .HasForeignKey("ReleasesUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_release_entity_site_tag_entity_releases_releases_uuid");

                    b.HasOne("CultureExtractor.SiteTagEntity", null)
                        .WithMany()
                        .HasForeignKey("TagsUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_release_entity_site_tag_entity_tags_tags_uuid");
                });

            modelBuilder.Entity("CultureExtractor.ReleaseEntity", b =>
                {
                    b.Navigation("Downloads");

                    b.Navigation("ExternalIds");
                });

            modelBuilder.Entity("CultureExtractor.SiteEntity", b =>
                {
                    b.Navigation("ExternalIds");

                    b.Navigation("StorageState");
                });

            modelBuilder.Entity("CultureExtractor.SitePerformerEntity", b =>
                {
                    b.Navigation("ExternalIds");
                });

            modelBuilder.Entity("CultureExtractor.SiteTagEntity", b =>
                {
                    b.Navigation("ExternalIds");
                });

            modelBuilder.Entity("CultureExtractor.SubSiteEntity", b =>
                {
                    b.Navigation("ExternalIds");
                });
#pragma warning restore 612, 618
        }
    }
}
